version: '3.8'

services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: otel-collector
    volumes:
      - /workspaces/latchflow/telemetry/configs:/etc/otelcol:ro
    command: ["--config=/etc/otelcol/otel-collector.yaml"]
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
    depends_on:
      - jaeger
      - prometheus

  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:1.52
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  # Prometheus for metrics storage
  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    ports:
      - "9090:9090"   # Prometheus UI
    volumes:
      - /workspaces/latchflow/telemetry/configs:/etc/prometheus-config:ro
    command:
      - '--config.file=/etc/prometheus-config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    ports:
      - "3000:3000"   # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./telemetry/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./telemetry/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./telemetry/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  grafana-storage:

networks:
  default:
    name: latchflow-telemetry_default