name: latchflow-svcs
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: latchflow
      POSTGRES_PASSWORD: latchflow
      POSTGRES_DB: latchflow
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  # minio, mailhog, etc. (also publish ports)
volumes:
  pgdata:
