version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: latchflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: latchflow
      POSTGRES_USER: latchflow
      POSTGRES_PASSWORD: latchflow
    ports:
      - "5432:5432"   # host:container
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U latchflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: latchflow-minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO console
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: latchflow-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

volumes:
  db-data:
  minio-data:
