import type { PolicyEntry } from "./types.js";

// Route signature helper: use the same signature literal when registering routes
// e.g. server.get("/plugins", requirePermission("GET /plugins")(handler))
export type RouteSignature = `${"GET" | "POST" | "PUT" | "PATCH" | "DELETE"} ${string}`;

export const POLICY: Record<RouteSignature, PolicyEntry> = {
  // Triggers (API paths; route code lives under admin)
  "GET /triggers": { action: "read", resource: "trigger_def", v1AllowExecutor: true },
  "POST /triggers": { action: "create", resource: "trigger_def" },
  "GET /triggers/:id": { action: "read", resource: "trigger_def", v1AllowExecutor: true },
  "PATCH /triggers/:id": { action: "update", resource: "trigger_def" },
  "DELETE /triggers/:id": { action: "delete", resource: "trigger_def" },
  "POST /triggers/:id/test-fire": { action: "update", resource: "trigger_def" },
  "GET /pipelines": { action: "read", resource: "pipeline", v1AllowExecutor: true },
  "POST /pipelines": { action: "create", resource: "pipeline" },
  "GET /pipelines/:id": { action: "read", resource: "pipeline", v1AllowExecutor: true },
  "PATCH /pipelines/:id": { action: "update", resource: "pipeline" },
  "DELETE /pipelines/:id": { action: "delete", resource: "pipeline" },
  "POST /pipelines/:id/steps": { action: "update", resource: "pipeline" },
  "PATCH /pipelines/:id/steps/:stepId": { action: "update", resource: "pipeline" },
  "DELETE /pipelines/:id/steps/:stepId": { action: "update", resource: "pipeline" },
  "POST /pipelines/:id/steps/reorder": { action: "update", resource: "pipeline" },
  "POST /pipelines/:id/triggers": { action: "update", resource: "pipeline" },
  "PATCH /pipelines/:id/triggers/:triggerId": { action: "update", resource: "pipeline" },
  "DELETE /pipelines/:id/triggers/:triggerId": { action: "update", resource: "pipeline" },
  "POST /pipelines/:id/triggers/reorder": { action: "update", resource: "pipeline" },
  "GET /pipelines/:id/versions": { action: "read", resource: "pipeline", v1AllowExecutor: true },
  "GET /pipelines/:id/versions/:version": {
    action: "read",
    resource: "pipeline",
    v1AllowExecutor: true,
  },
  "GET /users": { action: "read", resource: "user" },
  "POST /users": { action: "create", resource: "user" },
  "POST /users/invite": { action: "create", resource: "user" },
  "GET /users/:id": { action: "read", resource: "user" },
  "PATCH /users/:id": { action: "update", resource: "user" },
  "DELETE /users/:id": { action: "delete", resource: "user" },
  "GET /users/:id/sessions": { action: "read", resource: "user" },
  "POST /users/:id/revoke": { action: "update", resource: "user" },
  "GET /triggers/:id/versions": { action: "read", resource: "trigger_def", v1AllowExecutor: true },
  "POST /triggers/:id/versions": { action: "update", resource: "trigger_def" },
  "GET /triggers/:id/versions/:version": {
    action: "read",
    resource: "trigger_def",
    v1AllowExecutor: true,
  },
  "POST /triggers/:id/versions/:version/activate": { action: "update", resource: "trigger_def" },
  // Admin plugin management
  "GET /plugins": { action: "read", resource: "plugin", v1AllowExecutor: true },
  "POST /plugins/install": { action: "manage", resource: "plugin" },
  "DELETE /plugins/:pluginId": { action: "delete", resource: "plugin" },
  "GET /capabilities": { action: "read", resource: "capability", v1AllowExecutor: true },

  // Actions (admin API)
  "GET /actions": { action: "read", resource: "action_def", v1AllowExecutor: true },
  "POST /actions": { action: "create", resource: "action_def" },
  "GET /actions/:id": { action: "read", resource: "action_def", v1AllowExecutor: true },
  "PATCH /actions/:id": { action: "update", resource: "action_def" },
  "DELETE /actions/:id": { action: "delete", resource: "action_def" },
  "GET /actions/:id/versions": { action: "read", resource: "action_def", v1AllowExecutor: true },
  "POST /actions/:id/versions": { action: "update", resource: "action_def" },
  "GET /actions/:id/versions/:version": {
    action: "read",
    resource: "action_def",
    v1AllowExecutor: true,
  },
  "POST /actions/:id/versions/:version/activate": { action: "update", resource: "action_def" },
  "POST /actions/:id/test-run": { action: "update", resource: "action_def" },
  "GET /bundles": { action: "read", resource: "bundle", v1AllowExecutor: true },
  "POST /bundles": { action: "create", resource: "bundle" },
  "GET /bundles/:bundleId": { action: "read", resource: "bundle", v1AllowExecutor: true },
  "PATCH /bundles/:bundleId": { action: "update", resource: "bundle" },
  "DELETE /bundles/:bundleId": { action: "delete", resource: "bundle" },
  "GET /bundles/:bundleId/versions": { action: "read", resource: "bundle", v1AllowExecutor: true },
  "GET /bundles/:bundleId/versions/:version": {
    action: "read",
    resource: "bundle",
    v1AllowExecutor: true,
  },
  "GET /recipients": { action: "read", resource: "recipient", v1AllowExecutor: true },
  "POST /recipients": { action: "create", resource: "recipient" },
  "GET /recipients/:recipientId": { action: "read", resource: "recipient", v1AllowExecutor: true },
  "PATCH /recipients/:recipientId": { action: "update", resource: "recipient" },
  "DELETE /recipients/:recipientId": { action: "delete", resource: "recipient" },
  "GET /recipients/:recipientId/versions": {
    action: "read",
    resource: "recipient",
    v1AllowExecutor: true,
  },
  "GET /recipients/:recipientId/versions/:version": {
    action: "read",
    resource: "recipient",
    v1AllowExecutor: true,
  },
  "GET /bundles/:bundleId/recipients": {
    action: "read",
    resource: "bundle",
    v1AllowExecutor: true,
  },
  "POST /bundles/:bundleId/recipients": { action: "update", resource: "bundle" },
  "DELETE /bundles/:bundleId/recipients": { action: "update", resource: "bundle" },
  "POST /bundles/:bundleId/recipients/batch": { action: "update", resource: "bundle" },
  "GET /admin/bundles": { action: "read", resource: "bundle", v1AllowExecutor: true },
  "POST /admin/bundles/:bundleId/build": { action: "update", resource: "bundle" },
  "GET /admin/bundles/:bundleId/build/status": {
    action: "read",
    resource: "bundle",
    v1AllowExecutor: true,
  },
  "GET /admin/bundles/:bundleId/assignments": {
    action: "read",
    resource: "bundle",
    v1AllowExecutor: true,
  },
  "GET /admin/recipients": { action: "read", resource: "recipient", v1AllowExecutor: true },
  "GET /admin/recipients/:recipientId/assignments": {
    action: "read",
    resource: "recipient",
    v1AllowExecutor: true,
  },
  // Permission presets management
  "GET /admin/permissions/presets": { action: "read", resource: "user", v1AllowExecutor: true },
  "POST /admin/permissions/presets": { action: "create", resource: "user" },
  "GET /admin/permissions/presets/:id": { action: "read", resource: "user", v1AllowExecutor: true },
  "PATCH /admin/permissions/presets/:id": { action: "update", resource: "user" },
  "DELETE /admin/permissions/presets/:id": { action: "delete", resource: "user" },
  "GET /admin/permissions/presets/:id/versions": {
    action: "read",
    resource: "user",
    v1AllowExecutor: true,
  },
  "POST /admin/permissions/presets/:id/versions": { action: "update", resource: "user" },
  "GET /admin/permissions/presets/:id/versions/:version": {
    action: "read",
    resource: "user",
    v1AllowExecutor: true,
  },
  "POST /admin/permissions/presets/:id/versions/:version/activate": {
    action: "update",
    resource: "user",
  },
  // Permission simulation
  "POST /admin/permissions/simulate": { action: "read", resource: "user" },
  "GET /admin/triggers": { action: "read", resource: "trigger_def", v1AllowExecutor: true },

  // Files
  "GET /files": { action: "read", resource: "file", v1AllowExecutor: true },
  "GET /files/:id": { action: "read", resource: "file", v1AllowExecutor: true },
  "GET /files/:id/download": { action: "read", resource: "file", v1AllowExecutor: true },
  "POST /files/upload": { action: "create", resource: "file" },
  "POST /files/upload-url": { action: "create", resource: "file" },
  "POST /files/commit": { action: "create", resource: "file" },
  "PATCH /files/:id/metadata": { action: "update", resource: "file" },
  "POST /files/:id/move": { action: "update", resource: "file" },
  "DELETE /files/:id": { action: "delete", resource: "file" },
  "POST /files/batch/delete": { action: "delete", resource: "file" },
  "POST /files/batch/move": { action: "update", resource: "file" },

  // Bundle objects (admin)
  "GET /bundles/:bundleId/objects": { action: "read", resource: "bundle", v1AllowExecutor: true },
  "POST /bundles/:bundleId/objects": { action: "update", resource: "bundle" },
  "PATCH /bundles/:bundleId/objects/:id": { action: "update", resource: "bundle" },
  "DELETE /bundles/:bundleId/objects/:id": { action: "delete", resource: "bundle" },
} as const;
