/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/openapi.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Bundled OpenAPI document */
    get: operations["getOpenApi"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe */
    get: operations["getLiveness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness probe */
    get: operations["getReadiness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/admin/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start admin login via magic link */
    post: operations["startAdminLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/admin/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Finalize admin login using magic link token */
    get: operations["finalizeAdminLogin"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/admin/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout admin session */
    post: operations["logoutAdmin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current admin user */
    get: operations["getCurrentAdmin"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/whoami": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Identify current principal (admin or cli) */
    get: operations["whoAmI"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List active admin sessions for current user */
    get: operations["listAdminSessions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/sessions/revoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke a specific admin session */
    post: operations["revokeAdminSession"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/recipient/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start recipient OTP flow */
    post: operations["startRecipientOtp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/recipient/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify recipient OTP and establish session */
    post: operations["verifyRecipientOtp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/recipient/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout recipient session */
    post: operations["logoutRecipient"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/cli/device/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start CLI device authorization */
    post: operations["startCliDeviceAuth"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/cli/device/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve a CLI device using user code (admin/executor only) */
    post: operations["approveCliDevice"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/cli/device/poll": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Poll for device authorization result */
    post: operations["pollCliDevice"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/cli/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List API tokens for current admin/executor */
    get: operations["listCliTokens"];
    put?: never;
    /** Create a new API token */
    post: operations["createCliToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/cli/tokens/revoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke an API token */
    post: operations["revokeCliToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/cli/tokens/rotate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate an API token */
    post: operations["rotateCliToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List files */
    get: operations["listFiles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/files/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload file */
    post: operations["uploadFile"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/files/upload-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create pre-signed upload URL */
    post: operations["createUploadUrl"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/files/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get file by id */
    get: operations["getFile"];
    put?: never;
    post?: never;
    /** Delete file */
    delete: operations["deleteFile"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/files/{id}/move": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Move/rename file key */
    post: operations["moveFile"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/files/{id}/metadata": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update file metadata */
    patch: operations["updateFileMetadata"];
    trace?: never;
  };
  "/files/batch/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Batch delete files */
    post: operations["deleteFilesBatch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/files/batch/move": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Batch move files */
    post: operations["moveFilesBatch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/files/{id}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download file */
    get: operations["downloadFile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bundles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List bundles */
    get: operations["listBundles"];
    put?: never;
    /** Create bundle */
    post: operations["createBundle"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bundles/{bundleId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get bundle by id */
    get: operations["getBundle"];
    put?: never;
    post?: never;
    /** Delete bundle */
    delete: operations["deleteBundle"];
    options?: never;
    head?: never;
    /** Update bundle */
    patch: operations["updateBundle"];
    trace?: never;
  };
  "/bundles/{bundleId}/objects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List bundle objects */
    get: operations["listBundleObjects"];
    put?: never;
    /** Attach files to bundle */
    post: operations["attachBundleObjects"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bundles/{bundleId}/objects/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Detach bundle object */
    delete: operations["deleteBundleObject"];
    options?: never;
    head?: never;
    /** Update bundle object */
    patch: operations["updateBundleObject"];
    trace?: never;
  };
  "/recipients": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List recipients */
    get: operations["listRecipients"];
    put?: never;
    /** Create recipient */
    post: operations["createRecipient"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recipients/{recipientId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get recipient by id */
    get: operations["getRecipient"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bundles/{bundleId}/recipients": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List recipients assigned to a bundle */
    get: operations["listBundleRecipients"];
    put?: never;
    /** Attach recipient to bundle */
    post: operations["attachRecipientToBundle"];
    /** Detach recipient from bundle */
    delete: operations["detachRecipientFromBundle"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bundles/{bundleId}/recipients/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Attach multiple recipients to bundle */
    post: operations["attachRecipientsToBundleBatch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portal/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current recipient info */
    get: operations["getPortalMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portal/bundles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List bundles available to the recipient */
    get: operations["listPortalBundles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portal/bundles/{bundleId}/objects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List files in a bundle (recipient view) */
    get: operations["listPortalBundleObjects"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portal/bundles/{bundleId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download bundle (stream or redirect) */
    get: operations["downloadPortalBundle"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portal/auth/otp/resend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resend recipient OTP */
    post: operations["resendPortalOtp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/plugins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List registered plugins */
    get: operations["listPlugins"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/plugins/{pluginId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Uninstall plugin */
    delete: operations["uninstallPlugin"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/plugins/install": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Install plugin */
    post: operations["installPlugin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/capabilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List registered trigger/action capabilities */
    get: operations["listCapabilities"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/triggers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List trigger definitions */
    get: operations["listTriggers"];
    put?: never;
    /** Create trigger definition */
    post: operations["createTrigger"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/triggers/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete trigger definition */
    delete: operations["deleteTrigger"];
    options?: never;
    head?: never;
    /** Update trigger definition */
    patch: operations["updateTrigger"];
    trace?: never;
  };
  "/actions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List action definitions */
    get: operations["listActions"];
    put?: never;
    /** Create action definition */
    post: operations["createAction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/actions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete action definition */
    delete: operations["deleteAction"];
    options?: never;
    head?: never;
    /** Update action definition */
    patch: operations["updateAction"];
    trace?: never;
  };
  "/pipelines": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List trigger→action pipelines */
    get: operations["listPipelines"];
    put?: never;
    /** Create pipeline */
    post: operations["createPipeline"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pipelines/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete pipeline */
    delete: operations["deletePipeline"];
    options?: never;
    head?: never;
    /** Update pipeline */
    patch: operations["updatePipeline"];
    trace?: never;
  };
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List users/executors */
    get: operations["listUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{id}/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update user roles */
    patch: operations["updateUserRoles"];
    trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    /** @description Standard error envelope for all error responses */
    Error: {
      /**
       * @description Fixed string indicating an error response
       * @enum {string}
       */
      status: "error";
      /** @description Stable machine-readable error code */
      code: string;
      /** @description Human-friendly error description */
      message?: string;
      /** @description Optional extra data about the error */
      details?: {
        [key: string]: unknown;
      };
      /** @description Correlation identifier for logs/trace */
      requestId?: string;
    };
    Page: {
      items: Record<string, never>[];
      nextCursor?: string;
    };
    ObjectMeta: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt: string;
    };
    File: {
      /** Format: uuid */
      id: string;
      key: string;
      size: number;
      contentType: string;
      metadata?: {
        [key: string]: string;
      };
      etag?: string;
      /** Format: date-time */
      updatedAt: string;
    };
    Bundle: {
      /** Format: uuid */
      id: string;
      name: string;
      description?: string;
      /** Format: uuid */
      ownerId: string;
      /** Format: date-time */
      createdAt: string;
    };
    BundleObject: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      bundleId: string;
      /** Format: uuid */
      fileId: string;
      path?: string;
      sortOrder?: number;
      required?: boolean;
      /** Format: date-time */
      addedAt?: string;
    };
    BundleObjectWithFile: {
      bundleObject: components["schemas"]["BundleObject"];
      file: components["schemas"]["File"];
    };
    Recipient: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      displayName?: string;
    };
    Plugin: {
      /** Format: uuid */
      id: string;
      name: string;
      version: string;
      capabilities: components["schemas"]["Capability"][];
    };
    Capability: {
      /** @enum {string} */
      kind: "TRIGGER" | "ACTION";
      key: string;
      displayName: string;
      jsonSchema: Record<string, never>;
    };
    TriggerDefinition: {
      /** Format: uuid */
      id: string;
      capabilityKey: string;
      config: Record<string, never>;
      enabled: boolean;
      /** Format: date-time */
      createdAt?: string;
    };
    ActionDefinition: {
      /** Format: uuid */
      id: string;
      capabilityKey: string;
      config: Record<string, never>;
      enabled: boolean;
      /** Format: date-time */
      createdAt?: string;
    };
    TriggerAction: {
      /** Format: uuid */
      id: string;
      trigger: components["schemas"]["TriggerDefinition"];
      action: components["schemas"]["ActionDefinition"];
      /** Format: date-time */
      createdAt?: string;
    };
    User: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      roles: string[];
      /** Format: date-time */
      createdAt?: string;
    };
    DeviceStartResponse: {
      device_code: string;
      user_code: string;
      verification_uri: string;
      expires_in: number;
      interval: number;
    };
    DevicePollPending: {
      /** @enum {string} */
      status: "pending";
      interval: number;
    };
    DevicePollSuccess: {
      access_token: string;
      /** @enum {string} */
      token_type: "bearer";
      scopes: string[];
      /** Format: date-time */
      expires_at?: string;
    };
  };
  responses: {
    /** @description Unauthorized */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Forbidden */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Rate limited */
    RateLimited: {
      headers: {
        /** @description Seconds to wait before retrying */
        "Retry-After"?: number;
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Validation error */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /** @description Continuation cursor for pagination */
    Cursor: string;
    /** @description Page size */
    Limit: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
  getOpenApi: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OpenAPI JSON */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not bundled */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getLiveness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
    };
  };
  getReadiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
    };
  };
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            status: "ok";
            queue: string;
            storage: string;
          };
        };
      };
    };
  };
  startAdminLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
        };
      };
    };
    responses: {
      /** @description Magic link issued (no content) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
    };
  };
  finalizeAdminLogin: {
    parameters: {
      query: {
        token: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session established via cookie */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  logoutAdmin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logged out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  getCurrentAdmin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: components["schemas"]["User"];
            session?: Record<string, never>;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  whoAmI: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Identity */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            kind?: "admin" | "cli";
            user?: components["schemas"]["User"];
            scopes?: string[];
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  listAdminSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sessions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: {
              /** Format: uuid */
              id: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              expiresAt: string;
              /** Format: date-time */
              lastSeenAt?: string;
              ip?: string;
              userAgent?: string;
            }[];
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  revokeAdminSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: uuid */
          sessionId: string;
        };
      };
    };
    responses: {
      /** @description Revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  startRecipientOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          recipientId: string;
          bundleId: string;
        };
      };
    };
    responses: {
      /** @description OTP issued (dev logs only) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
    };
  };
  verifyRecipientOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          recipientId: string;
          bundleId: string;
          otp: string;
        };
      };
    };
    responses: {
      /** @description Session established via cookie */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      429: components["responses"]["RateLimited"];
    };
  };
  logoutRecipient: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logged out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  startCliDeviceAuth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email?: string;
          deviceName?: string;
        };
      };
    };
    responses: {
      /** @description Device auth started */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceStartResponse"];
        };
      };
      400: components["responses"]["ValidationError"];
      429: components["responses"]["RateLimited"];
    };
  };
  approveCliDevice: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          user_code: string;
        };
      };
    };
    responses: {
      /** @description Approved */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
    };
  };
  pollCliDevice: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          device_code: string;
        };
      };
    };
    responses: {
      /** @description Authorization complete */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DevicePollSuccess"];
        };
      };
      /** @description Authorization pending */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DevicePollPending"];
        };
      };
      429: components["responses"]["RateLimited"];
    };
  };
  listCliTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tokens list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            tokens: Record<string, never>[];
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  createCliToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          name?: string;
          scopes?: string[];
          ttlDays?: number;
        };
      };
    };
    responses: {
      /** @description Created; token is only returned once */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            token: string;
            /** Format: uuid */
            id: string;
            name?: string;
            scopes?: string[];
            /** Format: date-time */
            expiresAt?: string;
          };
        };
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  revokeCliToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          tokenId: string;
        };
      };
    };
    responses: {
      /** @description Revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  rotateCliToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: uuid */
          tokenId: string;
        };
      };
    };
    responses: {
      /** @description Rotated; new token returned once */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            token: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            expiresAt?: string;
          };
        };
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  listFiles: {
    parameters: {
      query?: {
        /** @description Page size */
        limit?: components["parameters"]["Limit"];
        /** @description Continuation cursor for pagination */
        cursor?: components["parameters"]["Cursor"];
        prefix?: string;
        q?: string;
        unassigned?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Files page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["File"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  uploadFile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          key?: string;
          /** Format: binary */
          file: string;
          contentType?: string;
          metadata?: {
            [key: string]: string;
          };
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["File"];
        };
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  createUploadUrl: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          key: string;
          contentType?: string;
          metadata?: {
            [key: string]: string;
          };
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            url: string;
            fields?: {
              [key: string]: unknown;
            };
            headers?: {
              [key: string]: unknown;
            };
            /** Format: date-time */
            expiresAt: string;
          };
        };
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  getFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["File"];
        };
      };
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["NotFound"];
    };
  };
  deleteFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  moveFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          newKey: string;
        };
      };
    };
    responses: {
      /** @description Moved */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  updateFileMetadata: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          metadata: {
            [key: string]: string;
          };
        };
      };
    };
    responses: {
      /** @description Updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  deleteFilesBatch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          ids: string[];
        };
      };
    };
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  moveFilesBatch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          items: {
            /** Format: uuid */
            id: string;
            newKey: string;
          }[];
        };
      };
    };
    responses: {
      /** @description Moved */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  downloadFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File stream */
      200: {
        headers: {
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  listBundles: {
    parameters: {
      query?: {
        /** @description Page size */
        limit?: components["parameters"]["Limit"];
        /** @description Continuation cursor for pagination */
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bundles page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["Bundle"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  createBundle: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          name: string;
          description?: string;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Bundle"];
        };
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  getBundle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bundle */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Bundle"];
        };
      };
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["NotFound"];
    };
  };
  deleteBundle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  updateBundle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundleId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          name?: string;
          description?: string;
        };
      };
    };
    responses: {
      /** @description Updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  listBundleObjects: {
    parameters: {
      query?: {
        /** @description Page size */
        limit?: components["parameters"]["Limit"];
        /** @description Continuation cursor for pagination */
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path: {
        bundleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bundle objects page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["BundleObjectWithFile"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  attachBundleObjects: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundleId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          | {
              /** Format: uuid */
              fileId: string;
              path?: string;
              sortOrder?: number;
              required?: boolean;
            }[]
          | {
              items: {
                /** Format: uuid */
                fileId: string;
                path?: string;
                sortOrder?: number;
                required?: boolean;
              }[];
            };
      };
    };
    responses: {
      /** @description Attached */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["BundleObject"][];
          };
        };
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  deleteBundleObject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundleId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Detached */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  updateBundleObject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundleId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          path?: string;
          sortOrder?: number;
          required?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  listRecipients: {
    parameters: {
      query?: {
        /** @description Page size */
        limit?: components["parameters"]["Limit"];
        /** @description Continuation cursor for pagination */
        cursor?: components["parameters"]["Cursor"];
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recipients page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["Recipient"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  createRecipient: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          displayName?: string;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Recipient"];
        };
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  getRecipient: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipientId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recipient */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Recipient"];
        };
      };
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["NotFound"];
    };
  };
  listBundleRecipients: {
    parameters: {
      query?: {
        /** @description Page size */
        limit?: components["parameters"]["Limit"];
        /** @description Continuation cursor for pagination */
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path: {
        bundleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bundle recipients page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["Recipient"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  attachRecipientToBundle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundleId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: uuid */
          recipientId: string;
        };
      };
    };
    responses: {
      /** @description Attached */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  detachRecipientFromBundle: {
    parameters: {
      query: {
        recipientId: string;
      };
      header?: never;
      path: {
        bundleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Detached */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  attachRecipientsToBundleBatch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundleId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          recipientIds: string[];
        };
      };
    };
    responses: {
      /** @description Attached */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  getPortalMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recipient identity and allowed bundles */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            recipient: components["schemas"]["Recipient"];
            bundles: {
              /** Format: uuid */
              bundleId?: string;
              name?: string;
            }[];
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  listPortalBundles: {
    parameters: {
      query?: {
        /** @description Page size */
        limit?: components["parameters"]["Limit"];
        /** @description Continuation cursor for pagination */
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bundles page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["Bundle"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  listPortalBundleObjects: {
    parameters: {
      query?: {
        /** @description Page size */
        limit?: components["parameters"]["Limit"];
        /** @description Continuation cursor for pagination */
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path: {
        bundleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Files in bundle */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["File"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  downloadPortalBundle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bundle archive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      /** @description Redirect to signed URL */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  resendPortalOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: uuid */
          recipientId: string;
          /** Format: uuid */
          bundleId: string;
        };
      };
    };
    responses: {
      /** @description Sent */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      429: components["responses"]["RateLimited"];
    };
  };
  listPlugins: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Plugins */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["Plugin"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  uninstallPlugin: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pluginId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  installPlugin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          source: string;
          verifySignature?: boolean;
        };
      };
    };
    responses: {
      /** @description Installing */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  listCapabilities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Capability registry */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["Capability"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  listTriggers: {
    parameters: {
      query?: {
        /** @description Page size */
        limit?: components["parameters"]["Limit"];
        /** @description Continuation cursor for pagination */
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Triggers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["TriggerDefinition"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  createTrigger: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          capabilityKey: string;
          config: Record<string, never>;
          enabled?: boolean;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TriggerDefinition"];
        };
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  deleteTrigger: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  updateTrigger: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          config?: Record<string, never>;
          enabled?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  listActions: {
    parameters: {
      query?: {
        /** @description Page size */
        limit?: components["parameters"]["Limit"];
        /** @description Continuation cursor for pagination */
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Actions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["ActionDefinition"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  createAction: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          capabilityKey: string;
          config: Record<string, never>;
          enabled?: boolean;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActionDefinition"];
        };
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  deleteAction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  updateAction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          config?: Record<string, never>;
          enabled?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  listPipelines: {
    parameters: {
      query?: {
        /** @description Page size */
        limit?: components["parameters"]["Limit"];
        /** @description Continuation cursor for pagination */
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Pipelines */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["TriggerAction"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  createPipeline: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: uuid */
          triggerId: string;
          /** Format: uuid */
          actionId: string;
          sortOrder?: number;
          enabled?: boolean;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TriggerAction"];
        };
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  deletePipeline: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  updatePipeline: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          sortOrder?: number;
          enabled?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
  listUsers: {
    parameters: {
      query?: {
        /** @description Page size */
        limit?: components["parameters"]["Limit"];
        /** @description Continuation cursor for pagination */
        cursor?: components["parameters"]["Cursor"];
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Users */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["User"][];
            nextCursor?: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  updateUserRoles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          roles: string[];
        };
      };
    };
    responses: {
      /** @description Updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthorized"];
    };
  };
}
