type: object
properties:
  id: { type: string, format: uuid }
  name: { type: string }
  description:
    oneOf:
      - { type: string }
      - { type: 'null' }
  isEnabled: { type: boolean }
  createdAt: { type: string, format: date-time }
  updatedAt: { type: string, format: date-time }
required: [id, name, isEnabled]
